apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage
          image: aksdeployment.azurecr.io/webpage:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
spec:
  selector:
    app: webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer